name: CI jobs to run

on:
  push:
    branches:
      - main
      - test-this-pr/**

jobs:
  run-tests:
    if: |
      (github.event_name == 'push') &&
      ((github.ref == 'refs/head/main') ||
      contains(github.ref, 'test-this-pr'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
  
      - name: Run tests
        run: |
          python -m pytest -vvv
  
  report-status:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Job status: ${{ needs.run-tests.result }}"
    
