name: Run test-this-pr action

on:
  issue_comment:
    types: [created]

jobs:
  test-action:
    runs-on: ubuntu-latest
    if: |
      (github.event.issue.pull_request != null) &&
      contains(github.event.comment.body, '/test-this-pr')
    steps:
      - uses: sgibson91/test-this-pr-action@test
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
