name: Run test-this-pr action

on:
  push:
    branches:
      - main
      - "test-this-pr/**"
  issue_comment:
    types: [created]

jobs:
  run-test-this-pr:
    runs-on: ubuntu-latest
    if: |
      (github.event.issue.pull_request != null) && contains(github.event.comment.body, '/test-this-pr')
    steps:
      - uses: sgibson91/test-this-pr-action@main
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
